jobs:
- deployment:
  displayName: Deploy to AKS
  pool:
    vmImage: ubuntu-latest
  environment: dev
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self     
        - task: KubernetesManifest@0
          displayName: Deploy
          inputs:
            action: 'deploy'
            kubernetesServiceConnection: 'Dev-default-1573432664222'
            namespace: 'azure-development'
            manifests: 'deployment.yml'
            containers: 'httpd'
