jobs:
- deployment:
  displayName: Deploy to AKS
  pool:
    vmImage: ubuntu-latest
  environment: dev
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self     
        - task: KubernetesManifest@0
          displayName: Deploy
          inputs:
            action: deploy
            namespace: azure-development
            manifests: manifests/deployment.yml
            containers: |
              httpd
